name: deploy

on:
  # 添加 workflow_run 触发器
  workflow_run:
    workflows: [ "Update Bing Wallpaper" ]
    branches: [ main ]
    types:
      - completed
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [ main ]
    paths-ignore: # 添加路径过滤
      - 'docs/壁纸/**'
      - 'target/**'
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # 选择要使用的 pnpm 版本
          version: 8
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Install WebP tools
        run: sudo apt-get update && sudo apt-get install -y webp

      - name: Convert images to WebP
        run: |
          find docs/.vuepress/public/images -type f -name "*.jpg" -exec sh -c 'cwebp -q 80 "$1" -o "${1%.jpg}.webp"' _ {} \;
          find docs/.vuepress/public/images -type f -name "*.jpg" -exec rm {} \;

      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm docs:build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}