# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  schedule:
    # 每天凌晨0点执行
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: current date
      run: date
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "574355578@qq.com"
         git config --local user.name "My Github Actions"
         git add -A  # 简化添加所有变更文件
         git commit -m "chore: 日常更新bing壁纸" || echo "没有新变更需要提交"
         git pull --rebase  # 添加 rebase 避免合并提交
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: main
